local harpoon = require("harpoon")
harpoon.setup()

local map = function(keys, func, desc, mode)
	mode = mode or "n"
	vim.keymap.set(mode, keys, func, { desc = "Harpoon: " .. desc })
end

map("<leader>a", function()
	harpoon:list():add()
end, "[A]dd")
map("<C-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, "[E]dit")
map("<C-j>", function()
	harpoon:list():select(1)
end, "Select 1")
map("<C-k>", function()
	harpoon:list():select(2)
end, "Select 1")
map("<C-h>", function()
	harpoon:list():select(3)
end, "Select 3")
map("<C-l>", function()
	harpoon:list():select(4)
end, "Select 4")
